### ISSUE TITLE
Create a 0.14 release

### ISSUE THREAD

**Issue by lukasgraf** [zopefoundation/z3c.saconfig#3]
Could someone please create a `0.14` release?

The version check in the current `0.13` release fails for versions of SQLAlchemy >= 1.0.0, and this has already been [fixed in master](https://github.com/zopefoundation/z3c.saconfig/commit/a3c25fe3a2a2636b65610f29383fd1c1e398d293) (resp. the version check has been removed alltogether when dropping support for SA < 0.5 in a later commit).

/cc @jfroche @faassen

**Comment by faassen** [comment]
I'm happy to give someone access rights on pypi for this project if you want to do a release.

**Comment by lukasgraf** [comment]
@faassen if you could add me as a package index maintainer on PyPi (Username: `lukasg`) that would be great.

I'd be doing the release using `zest.releaser`, so if necessary I would prepare the package (`setup.py`, changelog, ...) as required by `zest.releaser`.

**Comment by faassen** [comment]
I added you to pypi, thanks!

I used zest.releaser for z3c.saconfig in the past, so no problem. You may need to adjust the version number to get rid of a warning you get with newer setuptools.

**Comment by lukasgraf** [comment]
Excellent, thank you!

**Comment by lukasgraf** [comment]
Damn, I just realised I can't push to this repo because it's under https://github.com/zopefoundation (and I also haven't signed the Zope Contributors Agreement yet, just the ones for Plone core / collective).

In theory I could create the release and upload it to PyPi, and do the version bumps via a pull request, but that's weird and error prone. I'll see that I can get my papers in order ;-)

**Comment by lukasgraf** [comment]
I just created an [0.14 release](https://pypi.python.org/pypi/z3c.saconfig/0.14).
