### ISSUE TITLE
Release of Python 3 compatibility version .

### ISSUE THREAD

**Issue by nazrulworld** [zopefoundation/z3c.saconfig#6]
Do you have plan for next release soon?

**Comment by jamadden** [comment]
PyPI owners appear to be @faassen @jfroche @lukasg @optilude @lrowe

**Comment by nazrulworld** [comment]
@jamadden thanks for mentioning them . Would be nice for me if getting release soon as I am working on a product for python3 which depends on this product.

**Comment by jfroche** [comment]
Added you as owner, you should be able to release
