### ISSUE TITLE
Switch to semantic versioning scheme to next  release

### ISSUE THREAD

**Issue by nazrulworld** [zopefoundation/z3c.saconfig#8]
This is kind discussion about  semantic versioning. 
What do you think, can we use semantic versioning to next release?

**Comment by mgedmin** [comment]
Sure, why not?

What would that entail, specifically?  Changing 0.15.dev0 to 0.15.0.dev0 to get all the three parts?

(Just note that PEP-440 requirements for marking .dev versions are unfortunately incompatible with semver.org's, so while we may follow the spirit of SemVer, we cannot follow the letter.)

The major part being 0 means z3c.saconfig makes no promises about API stability, so I don't think anything else would change.

**Comment by nazrulworld** [comment]
@mgedmin agree with you. 
changing dev version from `0.16.dev0` to `0.16.0.dev0`
